### ISSUE TITLE
Bundle still depends on aws/aws-sdk-php 2.*

### ISSUE THREAD

**Issue by wcoppens** [platinumpixs/aws-symfony2-bundle#4]
The bundle is still depended on the aws/aws-sdk-php 2.* bundle version, however we currently reached version 3.* of the SDK. No major changes were made to the SDK beside some things for managing the AWS Lambda service.

This starts to have some compatibility issues with other bundles which do require 3.* (mostly newer bundles)

I currently see no reason to not upgrade to the 3.* version?

**Comment by pzorn** [comment]
New version has been published with support for version 3
